# Generated by Django 5.2.4 on 2025-09-10 10:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Event", "0008_alter_comment_options_report"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="report",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="event",
            name="likes",
            field=models.ManyToManyField(
                blank=True, related_name="liked_events", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
