# Generated by Django 5.2.4 on 2025-09-10 11:15

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Event", "0009_alter_report_options_event_likes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="likes",
        ),
        migrations.AlterUniqueTogether(
            name="eventattendance",
            unique_together={("user", "event")},
        ),
        migrations.AlterUniqueTogether(
            name="like",
            unique_together={("user", "event")},
        ),
    ]
