# Generated by Django 5.2.4 on 2025-09-12 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Event", "0010_remove_event_likes_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="comments_enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="comment",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="Event.event",
            ),
        ),
    ]
