# Generated by Django 5.2.4 on 2025-09-13 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Event", "0011_event_comments_enabled_alter_comment_event"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
