# Generated by Django 5.2.4 on 2025-09-21 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Event", "0012_comment_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="favicon",
            field=models.ImageField(
                blank=True, null=True, upload_to="category_favicons/"
            ),
        ),
    ]
