# Generated by Django 5.2.4 on 2025-09-23 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Event", "0013_category_favicon"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="status",
            field=models.CharField(default="upcoming", max_length=20),
        ),
    ]
