# Generated by Django 5.2.4 on 2025-09-23 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Event", "0014_event_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="status",
        ),
    ]
