# Generated by Django 5.2.4 on 2025-10-04 18:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Event", "0015_remove_event_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="likes",
            field=models.ManyToManyField(
                blank=True, related_name="liked_events", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
