# Generated by Django 5.2.4 on 2025-12-24 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Event", "0017_remove_event_comments_enabled_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="comments_enabled",
            field=models.BooleanField(default=True),
        ),
    ]
