# Generated by Django 5.2.4 on 2025-12-24 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Event", "0018_event_comments_enabled"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="event",
            options={"ordering": ["-created_at"]},
        ),
        migrations.RemoveField(
            model_name="event",
            name="likes",
        ),
    ]
