# Generated by Django 5.2.4 on 2025-12-29 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Event", "0021_alter_event_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="event_images/"),
        ),
    ]
