# Generated by Django 5.2.4 on 2026-01-09 16:56

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Event", "0024_remove_event_participants_eventregistration_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="report",
            unique_together={("user", "event")},
        ),
    ]
