# Generated by Django 5.2.4 on 2025-09-19 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0004_userconnection"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="Bio",
            field=models.TextField(blank=True),
        ),
    ]
