# Generated by Django 5.2.4 on 2025-10-04 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0005_profile_bio"),
    ]

    operations = [
        migrations.AlterField(
            model_name="batch",
            name="required_events",
            field=models.PositiveIntegerField(default=0, unique=True),
        ),
    ]
