# Generated by Django 5.2.4 on 2025-10-06 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0006_alter_batch_required_events"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="is_private",
            field=models.BooleanField(default=False),
        ),
    ]
