# Generated by Django 5.2.4 on 2025-10-08 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0007_profile_is_private"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="Fullname",
            field=models.TextField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name="profile",
            name="age",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="geneder",
            field=models.CharField(
                blank=True,
                choices=[("Male", "Male"), ("Female", "Female"), ("Other", "Other")],
                max_length=10,
            ),
        ),
    ]
