# Generated by Django 5.2.4 on 2025-10-08 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0008_profile_fullname_profile_age_profile_geneder"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="geneder",
            new_name="gender",
        ),
    ]
