# Generated by Django 5.2.4 on 2025-10-08 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0009_rename_geneder_profile_gender"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="Fullname",
            new_name="FullName",
        ),
        migrations.RenameField(
            model_name="profile",
            old_name="gender",
            new_name="Gender",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="age",
        ),
        migrations.AddField(
            model_name="profile",
            name="MobileNumber",
            field=models.PositiveIntegerField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="Age",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
