# Generated by Django 5.2.4 on 2025-10-10 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0010_rename_fullname_profile_fullname_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="batch",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="batch_images/"),
        ),
        migrations.AlterField(
            model_name="profile",
            name="MobileNumber",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
