# Generated by Django 5.2.4 on 2025-12-24 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0011_batch_image_alter_profile_mobilenumber"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="MobileNumber",
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
