# Generated by Django 5.2.4 on 2025-12-29 10:46

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0012_alter_profile_mobilenumber"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="image",
            field=cloudinary.models.CloudinaryField(
                default="default.jpg", max_length=255, verbose_name="image"
            ),
        ),
    ]
