# Generated by Django 5.2.4 on 2025-12-29 10:49

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0013_alter_profile_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="batch",
            name="image",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="batch_thumbnail"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="image",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="user_avatar"
            ),
        ),
    ]
