# Generated by Django 5.2.4 on 2026-01-09 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0014_alter_batch_image_alter_profile_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="is_blocked",
            field=models.BooleanField(default=False),
        ),
    ]
